name = "pingpulse"
main = "src/index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "pingpulse-db"
database_id = "bd86c029-0290-48c6-aa26-10fc55ba78f8"

[[r2_buckets]]
binding = "ARCHIVE"
bucket_name = "pingpulse-archive"

[[analytics_engine_datasets]]
binding = "METRICS"
dataset = "pingpulse-metrics"

[durable_objects]
bindings = [
  { name = "CLIENT_MONITOR", class_name = "ClientMonitor" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ClientMonitor"]

[[routes]]
pattern = "ping.beric.ca"
custom_domain = true

[triggers]
crons = ["0 */6 * * *"]

[assets]
directory = "./dashboard/dist"
not_found_handling = "single-page-application"

[vars]
ADMIN_JWT_SECRET = "change-me-in-secrets"
LATEST_CLIENT_VERSION = "1.0.3"
